name: cashless_cafe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/
    - data/
  fonts:
    - family: Cera Pro
      fonts:
        - asset: fonts/Cera-Pro.otf

